---
- hosts: all 
  become: true

  vars:
##    nodejs_version: "10.17"
    nodejs_version: "6.x"
    pip_install_packages: []
##      - name: docker-py


  roles:
    - geerlingguy.repo-epel
    - geerlingguy.git
    - geerlingguy.ansible
    - geerlingguy.docker
    - geerlingguy.pip
    - geerlingguy.nodejs
    - geerlingguy.awx
