---
# For Python 3, use python3-pip.
pip_package: python-pip
pip_executable: "{{ 'pip3' if pip_package.startswith('python3') else 'pip' }}"

pip_install_packages:
 - name: awscli
   version: "latest"
 - name: more-itertools
   version: "5.0.0"
## - docker-py
## - docker-compose
